name: client-inspect-code

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - '.github/workflows/client-inspect-code.yml'
      - "client/**"

jobs:
  client-inspect-code:
    name: コード静的解析client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Get list of changed files
        id: changed_files
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
            });
            const csFiles = files
              .map(file => file.filename)
              .filter(filename => filename.endsWith('.cs'));
            core.setOutput("files", csFiles.join("\n"));

      - name: Output changed files
        run: |
          echo "変更有りのC＃ファイル:"
          echo "${{ steps.changed_files.outputs.files }}"
      
      - name: inspectCode
        shell: bash
        run:
          bundle exec fastlane client-inspect-code include_files:"${{ steps.changed_files.outputs.include_files }}"
