name: Code Analysis with JetBrains InspectCode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_code:
    name: Run JetBrains InspectCode
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'  # 请根据需要指定 .NET 版本

      - name: Restore NuGet packages
        run: dotnet restore ./client/Applications.Runtime.csproj

      - name: Install JetBrains InspectCode
        run: |
          dotnet tool install --global JetBrains.ReSharper.GlobalTools
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run InspectCode
        run: jb inspectcode ./client/Applications.Runtime.csproj --output=./tools/Inspectcode/inspectcode.json

      - name: Upload InspectCode report
        uses: actions/upload-artifact@v2
        with:
          name: inspectcode-report
          path: ./tools/Inspectcode/inspectcode.json
